name: Build DEB Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-docker@v2

      - name: Build Docker image
        run: docker build -t my-docker-image .

      - name: Push Docker image to registry (optional)
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag my-docker-image ${{ secrets.DOCKER_REGISTRY }}/my-docker-image
          docker push ${{ secrets.DOCKER_REGISTRY }}/my-docker-image

